### ISSUE TITLE
Panics with "XOpenIM failed" when launching.

### ISSUE THREAD

**Issue by Celti** [fizyk20/4d-labyrinth#1]
Some googling suggests this might be a locale error, but I've verified with `LC_ALL=C` and various other combinations to no avail. I'm quite sure that my locales are properly in order.

```
celti@siduri ~/build/4d-labyrinth/4d-labyrinth :( $ RUST_BACKTRACE=1 target/debug/4d-labyrinth 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendCreationError(OsError("XOpenIM failed"))', ../src/libcore/result.rs:799
stack backtrace:
   1:     0x55e3bbeb919f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x55e3bbebc95d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x55e3bbebb8a2 - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x55e3bbebbe38 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x55e3bbebbcd2 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x55e3bbebbc10 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x55e3bbebbb91 - rust_begin_unwind
   8:     0x55e3bbef2b7f - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x55e3bbac1914 - core::result::unwrap_failed::h490a74b1527906a3
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x55e3bbaaf40e - <core::result::Result<T, E>>::unwrap::h7ff678d5e2b6e286
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:737
  11:     0x55e3bbb11199 - _4d_labyrinth::main::hba06dc56df0bc70c
                        at /home/celti/build/4d-labyrinth/4d-labyrinth/src/main.rs:44
  12:     0x55e3bbec4426 - __rust_maybe_catch_panic
  13:     0x55e3bbebb121 - std::rt::lang_start::h14cbded5fe3cd915
  14:     0x55e3bbb146f3 - main
  15:     0x7fceec653290 - __libc_start_main
  16:     0x55e3bba90df9 - _start
  17:                0x0 - <unknown>
```

**Comment by Celti** [comment]
strace to the rescue; it's failing because of: `access("/usr/share/X11/locale/iso8859-1/Compose", R_OK) = -1 ENOENT (No such file or directory)` — even though it shouldn't be trying to access _anything_ non-UTF-8 in terms of locale. I _think_ glium/glutin should be doing better error handling in this context, but I know little enough about X11 programming to be sure.
